config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tweeets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confiramtion)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confiramtion, :current_password)
  end

end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all.order("created_at DESC")
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = current_user.tweeets.build
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: 'navbar-item' do %>
          <h1 class="title is-5">Twittter</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'New Tweeet', root_path, class: "button is-info is-inverted" %>
              </p>
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p class="control">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
                </p>
              <% else %>
                <p class="control">
                  <%= link_to 'Sign In', new_user_session_path, class: 'button is-info' %>
                </p>
                <p class="control">
                  <%= link_to 'Sign Up', new_user_registration_path, class: 'button is-info' %>
                </p>

              <% end %>
            </div>
          </div>
        </div>
      </div>


    </nav>
    <%= yield %>

  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'tweeets/form' %>
    </div>
  </article>
<% end %>

<% @tweeets.each do | tweeet | %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <%= gravatar_image_tag(tweeet.user.email, size: 64, alt: tweeet.user.name) %>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= tweeet.user.name %></strong><br>
          <small>@<%= tweeet.user.username %></small><br>
          <p><%= tweeet.tweeet %></p>
        </div>
        <% if user_signed_in? %>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to tweeet, class: 'level-item' do %>
              <span class="icon">
                <i class="fa fa-link" area-hidden="true"></i>
              </span>
            <% end %>
            <%= link_to edit_tweeet_path(tweeet), class: 'level-item' do %>
              <span class="icon">
                <i class="fa fa-pencil" area-hidden="true"></i>
              </span>
            <% end %>
            <%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" }, class: 'level-item' do %>
              <span class="icon">
                <i class="fa fa-trash-o" area-hidden="true"></i>
              </span>
            <% end %>
          </div>
        </nav>
        <% end %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/tweeets/_form.html.erb
<%= simple_form_for(@tweeet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweeet, label: "Tweeet about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, placeholder: "Compose a new Tweeet...", autofocus: true %>
    </div>
  </div>
  <%= f.submit 'Tweeet it', class: "button is-info" %>
<% end %>

app/views/tweeets/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br>
              <small>@<%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweeets</p>
            <p class="title is-6"><%= current_user.tweeets.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">
              Followers
            </p>
            <p class="title is-6">
              456K
            </p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/tweeets/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">
      Trend 1
    </a>
    <a class="panel-block">
      Trend 2
    </a>
    <a class="panel-block">
      Trend 3
    </a>
    <a class="panel-block">
      Trend 4
    </a>
    <a class="panel-block">
      Trend 5
    </a>
    <a class="panel-block">
      Trend 6
    </a>
  </nav>
</div>

app/views/tweeets/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">
      Who to Follow
    </p>
    <span class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholder/64x64.png" alt="">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </span>
    <span class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholder/64x64.png" alt="">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </span>
    <span class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholder/64x64.png" alt="">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </span>
  </nav>
</div>

app/views/tweeets/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">
          Editing Tweeet
        </h1>
        <%= render 'form', tweeet: @tweeet %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/tweeets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/tweeets/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">
          Create a New Tweeet
        </h1>
        <%= render 'form', tweeet: @tweeet %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/tweeets/show.html.erb
<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>